//**********************************************************//
//                                                          //
//       Bold for Delphi Stub File                          //
//                                                          //
//       Autogenerated file for method implementations      //
//                                                          //
//**********************************************************//

// 
#include "ParentChildMappingClasses.hpp"

const AnsiString JETNAMES[] = {"F-22","F-15","F-16","Tornado","JAS Gripen","MiG-29","Su-27","Mirage"};
const AnsiString PROPNAMES[] = {"Mustang","Spitfire","Focke Wulf","Arado","Messerschmidt","Hurricane","Tempest","Polikarpov"};

void __fastcall TJet::CompleteCreate(void)
{
  TAircraft::CompleteCreate();
  ThrustVector = false;
  Name = JETNAMES[random(7)];

}

void __fastcall TPropeller::CompleteCreate(void)
{
  TAircraft::CompleteCreate();
  Name = PROPNAMES[random(7)];
}

 