//**********************************************************//
//                                                          //
//       Bold for Delphi Stub File                          //
//                                                          //
//       Autogenerated file for method implementations      //
//                                                          //
//**********************************************************//

// 
#include "ComboBoxClasses.hpp"

const AnsiString FIRSTNAME[] = {"John","Sarah","Paul","Anne","Steve","Edward","Mary","Bill","Elisabeth","Arthur","Lisa","Scott","Judy","Michael"};
const AnsiString LASTNAME[] = {"Wilkinson","McKenzie","Anderson","Shaw","Houston","Jackson","Miller","Woods"};

// Set random properties on create.
void __fastcall TPerson::CompleteCreate(void)
{
  TBusinessClassesRoot::CompleteCreate();
  Name = FIRSTNAME[random(14)] + " " + LASTNAME[random(7)];
}
 