//**********************************************************//
//                                                          //
//       Bold for Delphi Stub File                          //
//                                                          //
//       Autogenerated file for method implementations      //
//                                                          //
//**********************************************************//

// 
#include "DataSetExampleClasses.hpp"
const AnsiString FIRSTNAMES[] = {"Harry", "Peter", "David", "John", "James"};
const AnsiString LASTNAMES[] = {"Jones", "Flint", "McGregor", "Gates", "Clinton"};
const AnsiString STREETS[] = {"Bold Drive", "5th Avenue", "Rose Path", "Select Avenue", "Pebble Road"};

void __fastcall TBuilding::CompleteCreate(void)
{
  TBusinessClassesRoot::CompleteCreate();
  Address = STREETS[random(5)];
  ZipCode = random(9000) + 1000;
}

void __fastcall TPerson::CompleteCreate(void)
{
  TBusinessClassesRoot::CompleteCreate();
  FirstName = FIRSTNAMES[random(5)];
  LastName = LASTNAMES[random(5)];
}
 